
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"



class Solution {
public:
    char findTheDifference(string s, string t) {
        int s1,t1;
        char diff;
        s1 = t1 = 0;
        for(int i = 0; i<s.size(); i++)
        {
            s1 = s1 + int(s[i]);
        }
        
         for(int i = 0; i<t.size(); i++)
        {
            t1 = t1 + int(t[i]);
        }

        diff = t1-s1;

        return diff;
        
    }
};